#! /bin/sh

set -e

SERVICE="gameground"
DAEMON="${SERVICE}"
SHELLLIB="${HOME}/src/server/shell-lib"
PARSER="${HOME}/src/server/parse-sh"
STEP=0
STEP_FIRST=0
STEP_LAST=9999
EXECUTE_COMMANDS=""
DIR_ROOT=`pwd`

if [ ! -f ${SHELLLIB} ] ; then
	echo "no shell programming library found"
	exit 1
fi

. ${SHELLLIB}

must_exist ${PARSER}

. ${PARSER}

TARGET="${1}"

if [ "x${TARGET}" != "xdebug" -a "x${TARGET}" != "xrelease" ] ; then
	TARGET="release"
fi

if [ ! -d build ] ; then
	echo "you must start this script from \`gameground' root directory"
	exit 1
fi

JAIL="/home/${SERVICE}/"

conditional_immutable_off() {
	if [ -d ${1} ] ; then
		set +e
		chattr -f -R -i "${1}"
		set -e
	fi
}

conditional_immutable_on() {
	if [ -d ${1} ] ; then
		set +e
		chattr -f -R +i "${1}"
		set -e
	fi
}

conditional_umount() {
	MOUNTED=`awk '/\/home\/gameground\/proc/' /proc/mounts`
	if [ "x${MOUNTED}" != "x" ] ; then
		umount -f /home/${SERVICE}/proc
	fi
}

unset PS_FORMAT

adv ./_deploy/init stop
adv /bin/rm -fr nest
adv mkdir -p nest/etc/conf nest/var/db/yaal/keys
adv cp build/${TARGET}/${DAEMON}/1exec nest/
adv cp -a ${HOME}/usr/lib nest
adv cp -a ${HOME}/src/yaal/build/${TARGET}/yaalrc nest/etc/conf/
adv sed -i -e "s@${HOME}@\\\${HOME}@" nest/etc/conf/yaalrc
adv cp -a ${HOME}/src/${SERVICE}/gamegroundrc nest/etc/conf/
adv cp -a ${HOME}/src/${SERVICE}/gameground.sqlite nest/
adv cp -L ${HOME}/var/db/gameground/keys/* nest/var/db/yaal/keys/
adv cp -a ${HOME}/src/yaal/_aux/set-limits.sh nest
adv conditional_immutable_off ${JAIL}/nest
adv conditional_umount
adv /bin/rm -rf ${JAIL}/*
adv mkdir -p ${JAIL}/tmp ${JAIL}/bin

adv mv nest ${JAIL}/
adv cp -H /bin/sh ${JAIL}/bin/sh
adv cp -H /usr/bin/launchtool ${JAIL}/bin/
adv chmod 1757 ${JAIL}/tmp
adv chown -R root:root ${JAIL}/nest/
adv chown ${SERVICE}:service ${JAIL}/nest/ ${JAIL}/nest/gameground.sqlite ${JAIL}/tmp
adv chmod -R a+rX ${JAIL}/bin ${JAIL}/nest/*
adv makejail ./_deploy/jail-${DAEMON}.py
if [ ! -f ${JAIL}/etc/passwd ] ; then
	echo "Deployment failed!"
	exit 1
fi
adv /bin/rm -f ${JAIL}/nest/x_*
adv "grep service /etc/group > ${JAIL}/etc/group"
adv conditional_immutable_on ${JAIL}/nest
adv chattr -i ${JAIL}/nest ${JAIL}/nest/gameground.sqlite
adv ln -s urandom ${JAIL}/dev/random

