#! /bin/bash

set -e

SERVICE="gameground"
DAEMON="${SERVICE}"
SHELLLIB="${HOME}/src/server/shell-lib"
PARSER="${HOME}/src/server/parse-sh"
declare -i STEP=0
declare -i STEP_FIRST=0
declare -i STEP_LAST=9999
EXECUTE_COMMANDS=""
DIR_ROOT=`pwd`

if [ ! -f ${SHELLLIB} ] ; then
	echo "no shell programming library found"
	exit 1
fi

. ${SHELLLIB}

must_exist ${PARSER}

. ${PARSER}

if [ ! -d build ] ; then
	echo "you must start this script from \`gameground' root directory"
	exit 1
fi

JAIL="/home/${SERVICE}/"

conditional_chattr() {
	if [ -d ${1} ] ; then
		chattr -i ${1}/*
	fi
}

conditional_umount() {
	MOUNTED=`awk '/\/home\/gameground\/proc/' /proc/mounts`
	if [ "x${MOUNTED}" != "x" ] ; then
		umount -f /home/${SERVICE}/proc
	fi
}

adv ./_deploy/init stop
adv /bin/rm -fr nest
adv mkdir -p nest/etc/conf nest/var/db/keys
adv cp build/${DAEMON}/1exec nest/
adv cp -a ~/usr/lib nest
adv cp -a ~/src/yaal/yaalrc nest/etc/conf/
adv cp -a ~/src/${SERVICE}/gamegroundrc nest/etc/conf/
adv cp -a ~/var/db/keys/yaal.* nest/var/db/keys/
adv conditional_chattr ${JAIL}/nest "${JAIL}/nest/*"
adv conditional_umount
adv /bin/rm -rf ${JAIL}/*
adv mkdir -p ${JAIL}/tmp ${JAIL}/bin
adv mv nest ${JAIL}/
adv cp /bin/bash-minimal ${JAIL}/bin/sh
adv chmod 1757 ${JAIL}/tmp
adv chown -R root:root ${JAIL}/nest/
adv chown ${SERVICE}:service ${JAIL}/nest/ ${JAIL}/tmp
adv chmod -R a+rX ${JAIL}/bin ${JAIL}/nest/*
adv makejail ./_deploy/jail-${DAEMON}.py
if [ ! -f ${JAIL}/etc/passwd ] ; then
	echo "Deployment failed!"
	exit 1
fi
adv /bin/rm -f ${JAIL}/nest/x_*
adv "grep service /etc/group > ${JAIL}/etc/group"
adv chattr +i ${JAIL}/nest/*
adv ln -s urandom ${JAIL}/dev/random

